#!/bin/bash

doalarm () { perl -e 'alarm shift; exec @ARGV' "$@"; } # define a helper function

while true; do
  echo "waiting for IDLE"
  doalarm 30 python ~/.mutt/idle.py

  /usr/bin/notmuch tag -new -- tag:new

  echo "downloading new mail"
  doalarm 120 /usr/bin/offlineimap -a Ryan & pid1=$!
  doalarm 300 /usr/bin/offlineimap -a RH & pid2=$!
  wait $pid1
  /usr/local/notmuch new
  /usr/local/notmuch tag -new -- tag:new
  wait $pid2
  /usr/local/notmuch new
  /usr/local/notmuch tag -new -- tag:new

done
